<?php

namespace takielias\tp\Facades;

use Illuminate\Support\Facades\Facade;

class Tp extends Facade
{

    protected static function getFacadeAccessor()
    {
        // parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'takielias-tp';
    }

}
